Repository julianismaellunaarecha/akshu, pull requests merged in 2022-10, with the labels that each got.

#11 JS reemplazo de partes comunes de paginas de error
  assets/css/styles.css
  assets/error/contactoporerror.html
  assets/error/error400.html
  assets/error/error401.html
  assets/error/error403.html
  assets/error/error404.html
  assets/error/error405.html
  assets/error/error408.html
  assets/error/error410.html
  assets/error/error411.html
  assets/error/error412.html
  assets/error/error413.html
  assets/error/error414.html
  assets/error/error415.html
  assets/error/error500.html
  assets/error/error501.html
  assets/error/error502.html
  assets/error/error503.html
  assets/error/error506.html
  assets/js/errorpagestemplate.js
Labels: bug, enhancement

#10 9 mejorar el readmemd utilizando markdown
  README.md
  assets/icons/sonarcloudwhite.svg
  assets/img/acclogonicmail.png
  assets/img/codoacodoweb.png
  assets/img/flashhammerlogo.png
  assets/img/freednscrop.png
  assets/img/logotitleopengraphjenkins.png
Labels: documentation

#13 1 crear formulario de contacto en pagina de contacto
  assets/css/contacto.css
  contacto.html
Labels: enhancement

#17 Cambio nombrer de styles.css a navigationbar.css
  assets/css/navigationbar.css
  assets/error/contactoporerror.html
  assets/error/error400.html
  assets/error/error401.html
  assets/error/error403.html
  assets/error/error404.html
  assets/error/error405.html
  assets/error/error408.html
  assets/error/error410.html
  assets/error/error411.html
  assets/error/error412.html
  assets/error/error413.html
  assets/error/error414.html
  assets/error/error415.html
  assets/error/error500.html
  assets/error/error501.html
  assets/error/error502.html
  assets/error/error503.html
  assets/error/error506.html
  busqueda.html
  carrito.html
  contacto.html
  cuenta.html
  index.html
  notificaciones.html
  tienda.html
Labels: bug

#18 Reemplazo header con JS
  assets/js/pagestemplate.js
  busqueda.html
  carrito.html
  contacto.html
  cuenta.html
  index.html
  notificaciones.html
  tienda.html
Labels: enhancement

#20 Adecua visibilidad de barra de navegacion
  assets/css/body.css
  assets/css/navigationbar.css
  assets/error/contactoporerror.html
  assets/error/error400.html
  assets/error/error401.html
  assets/error/error403.html
  assets/error/error404.html
  assets/error/error405.html
  assets/error/error408.html
  assets/error/error410.html
  assets/error/error411.html
  assets/error/error412.html
  assets/error/error413.html
  assets/error/error414.html
  assets/error/error415.html
  assets/error/error500.html
  assets/error/error501.html
  assets/error/error502.html
  assets/error/error503.html
  assets/error/error506.html
  assets/js/pagestemplate.js
  busqueda.html
  carrito.html
  contacto.html
  cuenta.html
  index.html
  notificaciones.html
  tienda.html
Labels: enhancement

#22 Fix para barra de navegacion en paginas de error
  assets/js/errorpagestemplate.js
Labels: bug

#24 Fix de posicion de barra de navegacion
  assets/css/navigationbar.css
Labels: bug

#29 Propuesta estructura html
  assets/css/comun.css
  assets/css/error.css
  assets/icons/isologo.svg
  assets/js/errorpagestemplate.js
  assets/js/pagestemplate.js
  busqueda.html
  carrito.html
  contacto.html
  cuenta.html
  index.html
  notificaciones.html
Labels: documentation, enhancement

#37 30 arreglar la fijacion y tamaño del header y footer que se despliegan cuando se cambia el tamaño de la ventana
  assets/css/comun.css
  assets/css/contacto.css
  assets/css/error.css
  assets/css/index.css
  assets/css/navigationbar.css
  assets/error/error401.html
  assets/error/error403.html
  assets/error/error404.html
  assets/error/error414.html
  assets/error/error500.html
  assets/error/error503.html
  assets/error/error506.html
  assets/js/errorpagestemplate.js
  assets/js/pagestemplate.js
  contacto.html
  index.html
Labels: bug

#40 Integro api para traer productos.
  assets/css/index.css
  assets/js/productos.js
  index.html
Labels: enhancement

#45 quienes somos con grid, flex y animacion
  assets/css/quienesomos.css
  assets/img/julian.jfif
  assets/img/viviana.jfif
  assets/js/pagestemplate.js
  quienessomos.html
Labels: enhancement

#53 Servicios con tabla y JS
  SALVAR/servicios.css
  SALVAR/servicios.js
  assets/css/servicios.css
  assets/js/servicios.js
  servicios.html
Labels: enhancement
